services:
  backend:
    build: ./fica-backend 
    ports:
      - "8000:8000"
    volumes:
      - ./fica-backend:/app
  frontend:
    build: ./fica-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./fica-frontend:/app
    depends_on:
      - backend
  database:
    image: postgres:latest 
    env_file:
      - ./fica-backend/.env  
    enviroment: 
      - =your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
